plugin: community.digitalocean.digitalocean
oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
attributes:
  - id
  - name
  - tags
  - networks
compose:
  ansible_host: do_networks.v4 | selectattr('type','eq','public') | map(attribute='ip_address') | first
  ansible_user: 'root' # Assuming root is the user for Ubuntu 22.04 droplets
  ansible_ssh_common_args: '-o StrictHostKeyChecking=no' # For demonstration purposes; adjust as necessary for production
keyed_groups:
  - key: do_tags
    prefix: 'tag'

