plugin: community.digitalocean.digitalocean
oauth_token: "{{ lookup('env','DO_API_TOKEN') }}"
attributes:
  - id
  - name
  - tags
  - networks
compose:
  ansible_host: do_networks.v4 | selectattr('type','eq','public') | map(attribute='ip_address') | first
  ansible_user: 'root'
  ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
keyed_groups:
  - key: do_tags
    prefix: 'tag'

