---
- name: Provision DigitalOcean infrastructure
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../secrets/do_token.yml

  pre_tasks:
    - name: Include SSH key variables
      include_vars: 
        file: ../vars/ssh_keys.yml

  roles:
    - digitalocean_vpc
    - digitalocean_droplets
    # - digitalocean_firewall
   

