---
- name: Teardown DigitalOcean VPC
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../secrets/do_token.yml

  tasks:
    - name: Delete VPC by name
      community.digitalocean.digital_ocean_vpc:
        state: absent
        oauth_token: "{{ DO_API_TOKEN }}"
        name: hubbas

